### PR TITLE
Fail less hard on Java 11

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Maybe we should have these forks in https://github.com/scalacommunitybuild/ (and invite me to that) so I can push my changes directly.

**Comment by SethTisue** [comment]
yeah I try to only use my own personal forks temporarily. I see the community build config file has accumulated a number of such "temporary" forks, I've set a to-do to clean that up after my vacation.

and I just invited you to https://github.com/orgs/scalacommunitybuild/people

**Comment by dwijnand** [comment]
Thanks, Seth!

**Comment by dwijnand** [comment]
Moved to https://github.com/scalacommunitybuild/playframework/pull/1.

**Pull request closed without merging**
